### ISSUE TITLE
New ICON

### ISSUE THREAD

**Issue by BitzenyDevTeam** [BitzenyCoreDevelopers/bitzeny#1]
![bitcoin](https://user-images.githubusercontent.com/32291226/32265159-36fb532a-bf25-11e7-84b0-9b74c55bd99c.png)

**Comment by zenywallet** [comment]
Oh, Shodo!

We have to change the following image files.
share/pixmaps/bitcoin.ico
share/pixmaps/nsis-header.bmp
share/pixmaps/nsis-wizard.bmp
src/qt/res/icons/bitcoin.icns
src/qt/res/icons/bitcoin.ico
src/qt/res/icons/bitcoin.png
src/qt/res/icons/toolbar.png
src/qt/res/images/splash.png

**Comment by hitobb** [comment]
This request has been merged to z1.2.0.
Thanks.
