### ISSUE TITLE
The point to be fixed line of travis.yml with TravisCI

### ISSUE THREAD

**Issue by onokatio** [BitzenyCoreDevelopers/bitzeny#19]
https://travis-ci.org/BitzenyCoreDevelopers/bitzeny/jobs/326831409

```
1509: The command "cd bitcoin-$HOST" exited with 1.

6364: The command "./configure --cache-file=../config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)" exited with 1.

6520: The command "make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL V=1 ; false )" exited with 1.

6529: The command make -j3 check VERBOSE=1 exited with 2.

6584: The command "if [ "$RUN_TESTS" = "true" ]; then travis_wait 30 make $MAKEJOBS check VERBOSE=1; fi" exited with 2.

6602: The command "if [ "$RUN_TESTS" = "true" ]; then test/functional/test_runner.py --coverage --quiet ${extended}; fi" exited with 1.
```

I try fix.

**Comment by ghost** [comment]
fixed build errors
https://github.com/BitzenyCoreDevelopers/bitzeny/pull/15/commits/05b09e12f8d0bfaaee9b8c0e9563c2780b5163cb

We should fix broken tests.

**Comment by onokatio** [comment]
OK.
I think that passing automation build is needed than create test for bitzeny.
So first, I will edit travis.yml to not run test and check whether TravisCI run seccess.

How do you think ?

**Comment by ghost** [comment]
fixed errors and disabled tests
- https://github.com/BitzenyCoreDevelopers/bitzeny/pull/15/commits/59ee773d4d975c5894b5554b5677426822b3832d
- https://github.com/BitzenyCoreDevelopers/bitzeny/pull/15/commits/3d51e8e2470461757aa6023a4b56e32ff55f53e4

@BitzenyDevTeam Please modify tests for BitZeny and create PR.
