### ISSUE TITLE
There is "BTC/kB" units in the help message 

### ISSUE THREAD

**Issue by takaze** [BitzenyCoreDevelopers/bitzeny#20]
on Ubuntu 16.04

`console
./bitzenyd --help

...
Wallet options:
  -disablewallet
       Do not load the wallet and disable wallet RPC calls
  -keypool=<n>
       Set key pool size to <n> (default: 1000)
  -fallbackfee=<amt>
       A fee rate (in BTC/kB) that will be used when fee estimation has
       insufficient data (default: 0.0002)
  -discardfee=<amt>
       The fee rate (in BTC/kB) that indicates your tolerance for discarding
       change by adding it to the fee (default: 0.0001). Note: An output
       is discarded if it is dust at this rate, but we will always
       discard up to the dust relay fee and a discard fee above that is
       limited by the fee estimate for the longest target
  -mintxfee=<amt>
       Fees (in BTC/kB) smaller than this are considered zero fee for
       transaction creation (default: 0.00001)
....

`

**Comment by ghost** [comment]
fixed https://github.com/BitzenyCoreDevelopers/bitzeny/pull/15/commits/152f3e4bb5a43a2bbee1f8b34911bece5ae21c38#diff-51f643b7317a098f9241456eb3873fceR10

```
  -fallbackfee=<amt>
       A fee rate (in ZNY/kB) that will be used when fee estimation has
       insufficient data (default: 0.0002)
  -discardfee=<amt>
       The fee rate (in ZNY/kB) that indicates your tolerance for discarding
       change by adding it to the fee (default: 0.0001). Note: An output
       is discarded if it is dust at this rate, but we will always
       discard up to the dust relay fee and a discard fee above that is
       limited by the fee estimate for the longest target
  -mintxfee=<amt>
       Fees (in ZNY/kB) smaller than this are considered zero fee for
       transaction creation (default: 0.00001)
  -paytxfee=<amt>
       Fee (in ZNY/kB) to add to transactions you send (default: 0.00)
```
