### ISSUE TITLE
BTC-based message on RPC

### ISSUE THREAD

**Issue by Lesmiscore** [BitzenyCoreDevelopers/bitzeny#24]
### Describe the issue
BitZeny daemon (z2.0.0) will send you `deprecaution-message` with BTC-based version.

#### If so, please list the steps to reproduce below:
1. Make sure you enabled JSON RPC
2. Call `getinfo`
3. Check `$["deprecaution-warning"]`, you will see BTC-based warning

### Expected behaviour
To be removed, or replace with BitZeny-based version.

### Actual behaviour
See screenshots

### Screenshots.
![image](https://user-images.githubusercontent.com/10355528/35478875-4a120714-042c-11e8-8d1b-f27c0b7d4d6a.png)
(Don't care about passwords, since the environment is only for test.)

### What version of bitcoin-core are you using?
z2.0.0

### Machine specs:
- OS: Ubuntu 17.04
- CPU: Intel x64
- RAM: 2GB
- Disk size: 320GB
- Disk Type (HD/SDD): HDD

### Any extra information that might be useful in the debugging process.
Ref. https://github.com/BitzenyCoreDevelopers/bitzeny/blob/e9735bc37e03bdaebd23f46dc82167d72ccfdb12/src/rpc/misc.cpp#L90-L91

**Comment by ghost** [comment]
@nao20010128nao Thank you. It will be removed in a future release.

**Comment by ghost** [comment]
This endpoint has been removed on BitZeny 3.0 or later.
