### ISSUE TITLE
z2.0.0 release linux binary has error

### ISSUE THREAD

**Issue by mAKEkr** [BitzenyCoreDevelopers/bitzeny#28]
> ./bitzenyd: error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory

binaries displaying error, but am i already installed boost and boost-devel from yum repositories.
maybe check this error?
these error doesn't displaying on z1.2.1

Environment
OS : CentOS 7.4(x86_64 arch)

**Comment by Lesmiscore** [comment]
Can you please check the version of `Boost` you've installed?    
For example, Ubuntu 17.10 provides `1.62.0` instead of `1.58.0`.    

**EDIT:** Please paste the output of `yum info boost`.

**Comment by ghost** [comment]
@mAKEkr Sorry for your inconvenience. Please use static link version.
```bitzeny-2.0.0-x86_64-linux-gnu.tar.gz```
https://github.com/BitzenyCoreDevelopers/bitzeny/releases/tag/z2.0.0a

**Comment by mAKEkr** [comment]
@rmdfwqclmrkcvpbe completely fixing this error. thx! 👍
