### ISSUE TITLE
Message about first block chain synchronization

### ISSUE THREAD

**Issue by hitobb** [BitzenyCoreDevelopers/bitzeny#34]
### Describe the issue

I would like to add the following message to getinfo output.

```
Only at the first startup.
It may take several days before block chain synchronization begins for the caching the block header hash.
```

### Can you reliably reproduce the issue?
No.
This is my opinion about feature request.
I would like to discuss here.

### Expected behaviour
Many comments from bitzenyd users arrived that "bitzenyd block chain synchronization is not starting on z 2.0.0."

### Actual behaviour

After the hash cache is completed, bitzenyd blockchain synchronization  is starting .
This is the correct behavior.

Therefore,
I think it is better to add Information the output of getinfo command.

### What version of bitcoin-core are you using?
z2.0.0

### Any extra information that might be useful in the debugging process.

It is better to replace the message deleted by #24

```
"deprecation-warning", "WARNING: getinfo is deprecated and will be fully removed in 0.16." 
     " Projects should transition to using getblockchaininfo, getnetworkinfo, and getwalletinfo before upgrading to 0.16"
```
This is my opinion about feature request.
I would like to discuss here.

Thank you!

**Comment by ghost** [comment]
boo!
- The endpoint will be removed in next release.
- It is the well-known issue and also described in the release note.

If you want, you should add the message to another place.

**Comment by hitobb** [comment]
OK,I understand.
Thank you!
