### ISSUE TITLE
HD key generation is disabled on v2.0.1

### ISSUE THREAD

**Issue by cryptozeny** [BitzenyCoreDevelopers/bitzeny#40]
https://raw.githubusercontent.com/cryptozeny/image/master/20180319_024845.jpg

hi, i would to know what is it and why it disabled?

bitzeny v2.0.1
OS: ubuntu 16.04.4 64bit

**Comment by cryptozeny** [comment]
i found something about it. its a new feature since bitcoin v0.13.

https://bitcoin.org/en/release/v0.13.0

https://bitcointalk.org/index.php?topic=1665457.0

**Comment by ghost** [comment]
@cryptozeny Even if you re-use old wallet.dat, you can't get HD wallet. Perform the following steps to create new HD wallet.

1. dump wallet (Debug window)
```
dumpwallet foo
```
2. stop bitzenyd or BitZeny-QT
3. rename old wallet.dat
```
mv wallet.dat wallet.dat.old
```
4. start bitzenyd or BitZeny-QT
5. import wallet (Debug window)
```
importwallet foo
```
