### ISSUE TITLE
A 'sizeof' for a pointer issue

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [BitzenyCoreDevelopers/bitzeny#45]
Hi all,
There is a sizeof issue found by Qihoo360 CodeSafe Team.
Details as bellow:

https://github.com/BitzenyCoreDevelopers/bitzeny/blob/11f7e27a6a9967538b289f9918e71db37b933610/src/test/serialize_tests.cpp#L363
the argument of macro 'FLATDATA' is charstrval which is a pointer defined here:
https://github.com/BitzenyCoreDevelopers/bitzeny/blob/11f7e27a6a9967538b289f9918e71db37b933610/src/test/serialize_tests.cpp#L347
in the expand of macro 'FLATDATA' here:
https://github.com/BitzenyCoreDevelopers/bitzeny/blob/11f7e27a6a9967538b289f9918e71db37b933610/src/serialize.h#L354 
the parameter 'obj' will be used in sizeof operator.

do we really need the size of a pointer of should it be the size of the string (like strlen, or sizeof of a char array )?

Can you guys confirm this?

Cheers
Qihoo360 CodeSafe Team

**Comment by acid-chicken** [comment]
Dear @360CodeSafe ,

Thank you for letting us know about the problem!
We'll fix it later.

Many thanks,

Acid Chicken
Member, BitZeny Development team
